- ctrl + enter : 해당 셀 실행
- shift + enter : 실행 후 아래 셀로 넘어감

numpy 모듈 불러오기

In [3]:
import numpy as np

In [14]:
a = np.array(1)
a

array(1)

In [11]:
ndarr_1=np.array([1,2,3])
print(ndarr_1)

[1 2 3]


In [12]:
ndarr_2=np.array([1,2.0,3]) #하나라도 float 형태라면 모두 float으로 출력
print(ndarr_2)

[1. 2. 3.]


In [13]:
ndarr_3 = np.array([1,2.0,'3']) #하나라도 string이면 string으로 출력
print(ndarr_3)

['1' '2.0' '3']


자료형 확인
- dype

In [17]:
print(ndarr_1.dtype)
print(ndarr_2.dtype)
print(ndarr_3.dtype)

int32
float64
<U32


In [20]:
print(np.array(1+2j).dtype) # 허수 j를 넣었을때 복소수(complex)로 출력
print(np.array(print).dtype) # 객체로 출력

complex128
object


In [34]:
dtype1 = np.array([1,2,3], dtype=np.int8)
print(dtype1.dtype)

dtype2 = np.array([1,2,3],dtype=float)
print(dtype2.dtype)

dtype3 = np.array([1,2,3], dtype=str)
print(dtype3.dtype)

int8
float64
<U1


In [28]:
#주의할점
dtype4 = np.array([1,2.1,'3'],dtype=int)
print(dtype4)
print(dtype4.dtype)

[1 2 3]
int32


In [30]:
dtype5 = np.array([1,'data',print], dtype=float)
print(dtype5.dtype)

ValueError: could not convert string to float: 'data'

배열 크기 확인
- ndarray.shape

In [32]:
print(ndarr_1.shape)

(3,)


배열 차원 확인
- ndarray.ndim

In [33]:
print(ndarr_1.ndim)

1


- scalar : 숫자
- vector : 1차원 배열(scalar의 배열)
- metrix : 2차원 배열(vector의 배열)
- tensor : 3차원 배열(metrix의 배열)

배열 생성
- 1차원 배열 생성

In [35]:
vector = np.array([1,2,3])
print(vector)
print(vector.shape)
print(vector.ndim)
print(vector.dtype)

[1 2 3]
(3,)
1
int32


배열 생성
- 2차원 배열 생성

In [37]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.shape)   # 2행 3열
print(matrix.ndim)    # 차원 수
print(matrix.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


배열 생성
- 3차원 배열 생성

In [41]:
tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor)
print(tensor.shape)  
print(tensor.ndim)   # 차원 수
print(tensor.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3
int32


배열의 정보 확인
- 배열 요소의 개수 확인
    - ndarray.size

In [43]:
print(vector.size)
print(matrix.size)
print(tensor.size)

3
6
12


배열 생성

In [48]:
a = np.array([[1,2,3],[2,4,6],[3,6,9]])
print(a)
print(a.ndim)
print(a.size)
print(a.shape)

[[1 2 3]
 [2 4 6]
 [3 6 9]]
2
9
(3, 3)


자료형 변환(리스트)
- 리스트 -> ndarray
- ndarray -> 리스트
- 2차원 리스트 변환
- shape이 다른 리스트인 경우

In [94]:
#list -> ndarray
list1 = [1,2,3]
arr1 = np.array(list1)
print(arr1)

#ndarray -> list
arr2 = np.array([1,2,3])
list2 = list(arr2)
print(list2)

[1 2 3]
[1, 2, 3]


In [55]:
#주의할 점 = list의 shape이 다른 경우

list3 = [[1,2,3],[4,5,6]]
arr3 = np.array(list3)
print(arr3)


list4 = [[1,2,3,4],[5,6,7]]
arr4 = np.array(list4)
print(arr4)

[[1 2 3]
 [4 5 6]]
[list([1, 2, 3, 4]) list([5, 6, 7])]


C:\Users\admin\AppData\Local\Temp\ipykernel_4604\3028433119.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr4 = np.array(list4)


# 자료형 변환(튜플)

In [58]:
#tuple -> ndarray
tuple1 = (1,2,3)
arr = np.array(tuple1)
print(arr)

#ndarray -> tuple
arr2 = np.array([1,2,3])
tuple2 = tuple(arr2)
print(tuple2)

[1 2 3]
(1, 2, 3)


# 자료형 변환(세트, 딕셔너리)

In [60]:
set1 = {1,2,3}
arr = np.array(set1)
print(arr)
print(arr.size)

{1, 2, 3}
1


In [62]:
dict1 = {'a':1,'b':2,'c':3}
arr = np.array(dict1)
print(arr)
print(arr.size)

{'a': 1, 'b': 2, 'c': 3}
1


배열 인덱싱
- 리스트 인덱싱과 유사
- ndarray[col]
- ndarray[row][col]
- ndarray[rank][row][col]

In [66]:
list_=[[[1,2],[3,4]],[[5,6],[7,8]]]
#1 가져오기
print(list_[0][0][0])
#4 가져오기
print(list_[0][1][1])
# 7 가져오기
print(list_[1][1][0])

1
4
7


In [72]:
arr_ = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_)
#1 가져오기
print(arr_[0][0][0])
#4 가져오기
print(arr_[0][1][1])
# 7 가져오기
print(arr_[1][1][0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
4
7


In [75]:
arr_ = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_)
#1 가져오기
print(arr_[0,0,0])
#4 가져오기
print(arr_[0,1,1])
# 7 가져오기
print(arr_[1,1,0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
4
7


배열 인덱싱
- ndarray의 인덱싱
- ndarray[rank,row,col]

In [81]:
arr_1 = np.array([[1,2],          # 3 x 2 형태의 2차원 배열만들기
                 [3,4],
                 [5,6]])
print(arr_1)
#0행 가져와 2차원 배열만들기
print(arr_1[0])

#0,2행 가져와 2차원 배열만들기
print(arr_1[[0,2]])

#[] 차이로 출력되는 값 비교
print(arr_1[[0,1]]) # 0번째 배열의 1번쩨 헹까지의 2차원 배열로 출력
print(arr_1[0,1])   # 0번째 행에 1번째 값 출력

#다음 결과는?
print(arr_1[[0,1,2],
            [0,1,0]])   #row1,col1 = 0,0/   row2, col2=1,1    /row3, col3 

#같은 위치 데이터 여러번 사용 가능
print(arr_1[[0,0],[1,1]])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[[1 2]
 [5 6]]
[[1 2]
 [3 4]]
2
[1 4 5]
[2 2]


배열 인덱싱
- ndarray의 인덱싱

In [82]:
arr_2 = np.array([[1,2,3],         #4 x 3 형태의 2차원 배열
                 [4,5,6],
                 [7,8,9],
                 [10,11,12]])

b = np.array([0,1,2,3])
c = np.array([0,2,0,1])

print(arr_2[b,c])  #[(0,0),(1,2),(2,0),(3,1)] 의 값 출력 -- > [1,6,7,11]

[ 1  6  7 11]


배열 인덱싱
- Boolean 인덱싱

In [83]:
arr = np.array([1,2,3,4,5])

#true, false
print(arr[[True,False,True,True,False]])

# 조건
print(arr[arr>=3])

[1 3 4]
[3 4 5]


In [93]:
#문제2
score = np.array([[78,91,84,89,93,65],
                 [82,87,96,79,91,73]])

#score[0] : score 0행

print(score[0][score[0] >= 90])
print(score[1][score[1] >= 90])

[91 93]
[96 91]


배열 슬라이싱
- ndarray의 슬라이싱
- 행과 열 부분을 나눠서 슬라이싱 가능
- 다차원 배열의 부분 데이터를 추출할 때 유용

In [4]:
# 기본 데이터 4 x 5 형태의 2차원 배열
matrix = np.array([ [1,2,3,4,5],
                    [6,7,8,9,10],
                    [11,12,13,14,15],
                    [16,17,18,19,20] ])

In [15]:
#0열 전체 슬라이싱
print(matrix[:,0])

#0열 전체 슬라이싱(2차원 유지)
print(matrix[:,:1])
print(matrix[:,[0]])

[ 1  6 11 16]
[[ 1]
 [ 6]
 [11]
 [16]]
[[ 1]
 [ 6]
 [11]
 [16]]


In [16]:
#1행 전체 슬라이싱
print(matrix[1,:])
print(matrix[1])
print(matrix[1:2,:])   #2차원 유지
print(matrix[[1]])     #2차원 유지

[ 6  7  8  9 10]
[ 6  7  8  9 10]
[[ 6  7  8  9 10]]
[[ 6  7  8  9 10]]


In [18]:
#3~4열 전체 슬라이싱
print(matrix[:,3:])

#0행, 1~3열 슬라이싱
print(matrix[0,1:-1])

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]
[2 3 4]


In [21]:
matrix = np.array([ [1,2,3,4,5],
                    [6,7,8,9,10],
                    [11,12,13,14,15],
                    [16,17,18,19,20] ])
#2~3행, 2~4열 슬라이싱

print(matrix[-2:,-3:])

#1~2행 1~2열 슬라이싱
print(matrix[1:-1,1:3])

[[13 14 15]
 [18 19 20]]
[[ 7  8]
 [12 13]]


In [24]:
#1~3행, 2~4열 슬라이싱
print(matrix[[1,3],2:])

#1~2행, 1,3열 슬라이싱
print(matrix[1:-1,[1,3]])

[[ 8  9 10]
 [18 19 20]]
[[ 7  9]
 [12 14]]


배열 부분 추출 예제

In [4]:
tensor = np.array([ [ [1,2,3],[4,5,6]] , [ [7,8,9],[10,11,12] ] ] )
tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
print(tensor[[1,0,0],[1,0,1],[0,1,2]])

print(tensor[0, : ,:2])  #tensor[rank,raw,col]   , 0은 생략가능

print(tensor[1, :, 2])

[10  2  6]
[[1 2]
 [4 5]]
[ 9 12]
