# Reshape
- 배열의 shape을 변형해주는 함수
- 배열의 요소 개수를 유지하며 형태만 변경
- 변형 전 size와 변형 후 size가 동일해야함

In [218]:
import numpy as np

In [8]:
arr = np.array([[1,2,3],[4,5,6]]) # 2x3
print(arr)
print(arr.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [10]:
print(arr.reshape(3,1,2))
print(arr.reshape(-1,2))

[[[1 2]]

 [[3 4]]

 [[5 6]]]
[[1 2]
 [3 4]
 [5 6]]


In [12]:
print(arr.reshape(2,-1))

[[1 2 3]
 [4 5 6]]


In [15]:
tensor = np.array(range(1,37))            #shape (3,3,4)

print(tensor.reshape(3,3,4))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


# tensor 배열을 2차원 배열로 변형시켜봅니다. *열의 개수는 9

In [17]:
print(tensor.reshape(4,9))
print(tensor.reshape(-1,9))    # 행의 값에 -1을 넣을 경우 열에 맞춰서 배열을 생성해주세요

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]]
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]]


# Flatten
- 다차원 배열을 1차원 배열로 변형

In [26]:
print(arr)
print(arr.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [22]:
print(arr.reshape(1,6).flatten())

[1 2 3 4 5 6]


In [24]:
print(arr.reshape(3,1,2).flatten())

[1 2 3 4 5 6]


In [29]:
#tensor = np.array(range(1,37)) 
print(tensor.reshape(-1,9).flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


# Arange

In [35]:
print(np.arange(30))        #np.array(range(30)) 과 동일

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [39]:
#간격 지정 : np.arrange(start, end, step)
print(np.arange(0,10,2))

print(np.arange(-2,2,0.5))

print(np.arange(10,0,-1))

[0 2 4 6 8]
[-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5]
[10  9  8  7  6  5  4  3  2  1]


# Arange + Reshape
- 배열 요소를 순서대로 가지는 다차원 배열 생성 가능

In [41]:
print(np.arange(1,26).reshape(5,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [43]:
print(np.arange(0,6,0.2).reshape(3,2,5))

[[[0.  0.2 0.4 0.6 0.8]
  [1.  1.2 1.4 1.6 1.8]]

 [[2.  2.2 2.4 2.6 2.8]
  [3.  3.2 3.4 3.6 3.8]]

 [[4.  4.2 4.4 4.6 4.8]
  [5.  5.2 5.4 5.6 5.8]]]


In [45]:
print(np.arange(100,191,10).reshape(2,5))  #100~190, 10간격으로 shape(2,5)

[[100 110 120 130 140]
 [150 160 170 180 190]]


In [57]:
#-2 ~ 2, 0.5 3차원
np.arange(-2,2.5,0.5)
np.arange(-2,2.5,0.5).size
print(np.arange(-2,2.5,0.5).reshape(1,3,3))   # 3차원
print(np.arange(-2,2.5,0.5).reshape(3,3))  # 2차원

[[[-2.  -1.5 -1. ]
  [-0.5  0.   0.5]
  [ 1.   1.5  2. ]]]
[[-2.  -1.5 -1. ]
 [-0.5  0.   0.5]
 [ 1.   1.5  2. ]]


# Zeros
- 0으로 채워진 배열 생성

In [63]:
#np.zeros(shape.dtype)
print(np.zeros(shape=(5,),dtype=np.int8))

print(np.zeros((5),np.int8))

print(np.zeros((2,3)))  #dtype 생략하여 생성 가능 -> float으로 생성
print(np.zeros((2,3)).dtype)

[0 0 0 0 0]
[0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]]
float64


# Ones
- 1로 채워진 배열 생성

In [66]:
print(np.ones(shape=(5,),dtype=np.int8))

[1 1 1 1 1]


# Empty
- shape만 주어지고 비어있는 배열 생성
- 배열을 생성만 하고 값을 주지 않아 메모리에 저장되어 있던 기존값이 저장될 수 있음

In [73]:
print(np.empty(shape = (10,),dtype = np.int32))

[100 110 120 130 140 150 160 170 180 190]


# Zeros_like / Ones_like / Empty_like
- 입력 받은 배열과 같은 shape,dtype의 배열 생성

In [75]:
matrix = np.arange(24).reshape(4,6)
print(np.zeros_like(matrix))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [79]:
matrix = np.arange(-2,2,0.2).reshape(2,10)
matrix
print(np.ones_like(matrix))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [78]:
matrix = np.arange(30).reshape(5,6)
print(np.empty_like(matrix))

[[1411174936        461         73          0          0          0]
 [         0          0          0    7602297 1634607739  975332717]
 [1953702432 1953853284  572533794 1954047348  572537378  808464731]
 [ 808530208  808595744  808661280  808726816  808792352  808857888]
 [ 808923424  808988960  809054496  577657949    7078013          0]]


# Identity
- 단위 행렬 : 주대각선의 값이 1이고 나머지는 0인 정사각 행렬

In [83]:
print(np.identity(5,dtype=np.int8))
print(np.identity(5,dtype=np.str_))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[['1' '' '' '' '']
 ['' '1' '' '' '']
 ['' '' '1' '' '']
 ['' '' '' '1' '']
 ['' '' '' '' '1']]


In [82]:
print(np.identity(2))

[[1. 0.]
 [0. 1.]]


# Eye
- 대각선이 1로 채워지는 행렬
- 대각선의 시작 위치 지정 가능

In [85]:
print(np.eye(5,dtype=np.int8))     #np.eye(size,M,k,dtype)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [87]:
print(np.eye(5,k=2))

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [89]:
print(np.eye(5,M=10,k=-1))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


In [93]:
print(np.eye(5, M=10, k=-1))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


In [95]:
print(np.eye(5, M=10, k = 5))

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


# Full
- 입력값으로 채워지는 행렬

### np.full((shape),value)

In [97]:
print(np.full((2,5),3))

[[3 3 3 3 3]
 [3 3 3 3 3]]


# Random.randint
- 주어진 범위 안의 랜덤한 값을 뽑는 함수

### np.random.randint(range)

In [101]:
#0~5 까지의 정수 중 하나 뽑기
#numpy를 활용하여 랜덤하게 정수 뽑기
print(np.random.randint(6))

3


In [103]:
#random을 활용하여 랜덤하게 정수 뽑기
import random
random.randint(1,10)

6

# Random.rand
- 랜덤한 값으로 채워지는 배열
- 표준정규분포 난수를 shape 형태의 배열로 생성
- 0~1 사이의 값을 가짐

### np.random.rand(shape)

In [105]:
print(np.random.rand(3))

[0.15169382 0.03564282 0.56800299]


In [107]:
print(np.random.rand(3,2))

[[0.8168965  0.69513993]
 [0.83953245 0.51312981]
 [0.4862603  0.24044702]]


# Random.randn
- 랜덤한 값으로 채워지는 배열

### np.random,randn(shape)

In [109]:
print(np.random.randn(3))

[ 0.703633    0.67159121 -0.46314208]


In [111]:
print(np.random.randn(3,2))

[[ 1.19817928  0.21036248]
 [-0.84434531  0.67742441]
 [ 1.56342471  0.27012129]]


# 연산함수

## SUM

### ndarray.sum()

In [116]:
matrix=np.arange(1,7).reshape(2,3)
print(matrix)
print(matrix.sum())

[[1 2 3]
 [4 5 6]]
21


In [117]:
print(matrix.sum(axis=0))           # 'axis = 0' 열끼리 값을 더함
print(matrix.sum(axis=1))           # 'axis = 1' 행끼리 값을 더함

[5 7 9]
[ 6 15]


In [120]:
tensor=np.arange(1,19).reshape(3,2,3)
print(tensor)
print(tensor.sum())

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
171


In [122]:
print(tensor.sum(axis=0))
print(tensor.sum(axis=1))
print(tensor.sum(axis=2))

[[21 24 27]
 [30 33 36]]
[[ 5  7  9]
 [17 19 21]
 [29 31 33]]
[[ 6 15]
 [24 33]
 [42 51]]


# Mean

In [124]:
print(matrix.mean())           # 전체평균
print(matrix.mean(axis=0))     # 행끼리 평균
print(matrix.mean(axis=1))     # 열끼리 평균

3.5
[2.5 3.5 4.5]
[2. 5.]


In [126]:
tensor.sum()         #np.sum(tensor)

171

In [132]:
print(np.sum(tensor,axis=0))
print(tensor.sum(axis=0))

[[21 24 27]
 [30 33 36]]
[[21 24 27]
 [30 33 36]]


In [133]:
print(matrix.mean(axis=1))

[2. 5.]


# Std

In [136]:
print(matrix.std())
print(matrix.std(axis=0))
print(matrix.std(axis=1))

1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


# 그 외 수학 연산자
#### 지수(exp)
#### 로그(log)
#### 제곱근(sqrt)
#### 삼각함수(sin)
#### 삼각함수(cos)
#### 삼각함수(tan)

# 배열 정렬(Sort)

In [139]:
#randint를 사용하여 1~100 숫자 중 5개를 뽑아 배열 생성
vector = np.array([np.random.randint(1,100)
                  for n in range(5)])
print(vector)

[60 31 56  4 79]


In [141]:
print(np.sort(vector))

[ 4 31 56 60 79]


In [143]:
print(np.sort(vector)[::-1])

[79 60 56 31  4]


In [144]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [149]:
#리스트 내 포문
list_ = [1,2,3,4,5,6,7,8,9,10]

list2_= [num*3 for num in list_ if num % 2 ==1]
list2_

[3, 9, 15, 21, 27]

In [151]:
matrix = np.array([np.random.randint(1,100)
                  for n in range(20)]).reshape(4,5)
print(matrix)

[[18 59 35 14 36]
 [70 30 57 33 31]
 [78 96 26 12 33]
 [ 7 22 60  8 88]]


In [153]:
print(np.sort(matrix))
print(np.sort(matrix, axis = 0))

[[14 18 35 36 59]
 [30 31 33 57 70]
 [12 26 33 78 96]
 [ 7  8 22 60 88]]
[[ 7 22 26  8 31]
 [18 30 35 12 33]
 [70 59 57 14 36]
 [78 96 60 33 88]]


# 배열 합치기(Vstack)
### np.vstack([arr1,arr2])

In [156]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

print(np.vstack([vector1,vector2]))

[[1 2 3]
 [4 5 6]]


# Hstck
### np.hstack([arr1,arr2])

In [160]:
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)

print(np.hstack([vector1,vector2]))

[[1 4]
 [2 5]
 [3 6]]


# 배열 합치기(Concatenate)
### np.concatenate(arr1,arr2,axis)

## 주피터노트북 자동완성 : tab키 (파이썬에서 ctrl+space)

In [163]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
print(np.concatenate([vector1,vector2],axis=0))   # axis = 0 : 수평으로 합침 --> axis=1(수직) 은 오류

#concatenate : 1차원 배열에서는 수직으로 합칠때(axis=1) 오류 발생
#배열을 2차원으로 변경 후 axis=1로 성정하면 오류 해결

vector1 = np.array([[1,2,3]])
vector2 = np.array([[4,5,6]])
print(np.concatenate([vector1,vector2],axis=1))

[1 2 3 4 5 6]
[[1 2 3 4 5 6]]


In [174]:
matrix1 = np.array([[1,2,3],[1,2,3]]).reshape(3,2)
vector2 = np.array([[4,5,6]]).reshape(3,1)

print(np.concatenate[matrix1,vector2], axis=0)

TypeError: 'function' object is not subscriptable

In [169]:
matrix1 = np.arange(1,5).reshape(2,2)
matrix2 = np.arange(5,9).reshape(2,2)
print(np.concatenate([matrix1,matrix2],axis=1))

[[1 2 5 6]
 [3 4 7 8]]


# 행 / 열 바꾸기(transpose)
### ndarray.tranpose()
### ndarray.T

In [176]:
matrix3 = np.array([[5,6]])
print(matrix3)

[[5 6]]


In [181]:
print(matrix3.shape,matrix3.transpose().shape)
print(matrix3.transpose())
print(matrix3.T)

(1, 2) (2, 1)
[[5]
 [6]]
[[5]
 [6]]


In [184]:
np.array([[[5,6]]]).T.shape

(2, 1, 1)

# Transpose + Concatenate
- 형태를 바꿔 서로 결합할 수 없는 배열을 합칠 수 있다

In [230]:
print(np.concatenate([matrix1,matrix3]))

[[1 2]
 [3 1]
 [2 3]
 [5 6]]


In [221]:
print(np.concatenate([matrix1,matrix3],axis = 0))

# matrix1은 2 x 2 행렬  matrix3는 1행 2열 행렬
# 수평으로 결합(axis=1)하려면 행의 개수가 동일해야함 --> 결합이 안되므로 오류 발생

[[1 2]
 [3 1]
 [2 3]
 [5 6]]


In [224]:
print(np.concatenate([matrix1, matrix3.T], axis=0))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

# 인덱스 반환 함수
- argmax, agrmin

In [199]:
a = np.arange(1,11).reshape(2,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [201]:
print(np.argmax(a),np.argmin(a))

9 0


In [207]:
print(np.argmax(a,axis=0))

[1 1 1 1 1]


In [210]:
b = np.array([[1,2,3,4],[2,3,4,1],[3,4,1,2]])
print(b)
print(np.argmax(b,axis=1))
print(np.argmax(b,axis=0))

[[1 2 3 4]
 [2 3 4 1]
 [3 4 1 2]]
[3 2 1]
[2 2 1 0]


# 배열 인덱싱(Fancy Index)

In [212]:
a = np.arange(1,11)
b = np.array([3,4,5,6])
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5 6]


In [214]:
print(a[b])

[4 5 6 7]


In [216]:
a = np.arange(10,20)
b = np.argmax(a)
print(a)
print(b)

[10 11 12 13 14 15 16 17 18 19]
9


In [217]:
print(a[b])

19
