# 산술연산

In [65]:
import numpy as np

In [4]:
#리스트 덧셈
list1 = [1,2,3]
list2 = [4,5,6]
print(list1+list2)

[1, 2, 3, 4, 5, 6]


In [6]:
#배열의 덧셈
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)

[5 7 9]


In [9]:
#모양이 같은 배열연산
arr1 = np.arange(1,7,dtype=np.float32).reshape(2,3)
arr2 = np.arange(11,17,dtype=np.int32).reshape(2,3)
print(arr1+arr2)
print(arr2-arr1)

[[12. 14. 16.]
 [18. 20. 22.]]
[[10. 10. 10.]
 [10. 10. 10.]]


In [12]:
print(arr1*arr2)
print(arr2/arr1)
print(arr1**arr2)   # 제곱

[[11. 24. 39.]
 [56. 75. 96.]]
[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]]
[[1.00000000e+00 4.09600000e+03 1.59432300e+06]
 [2.68435456e+08 3.05175781e+10 2.82110991e+12]]


In [18]:
num=5
print(num**2)

25


In [23]:
print(arr2//arr1)  #몫
print(arr2 % arr1)  #나머지

[[11.  6.  4.]
 [ 3.  3.  2.]]
[[0. 0. 1.]
 [2. 0. 4.]]


In [32]:
print(np.add(arr1,arr2)) # 더하기
print(np.subtract(arr1,arr2)) # 빼기
print(np.multiply(arr1,arr2)) # 곱하기
print(np.divide(arr1,arr2)) # 나누기

[[12. 14. 16.]
 [18. 20. 22.]]
[[-10. -10. -10.]
 [-10. -10. -10.]]
[[11. 24. 39.]
 [56. 75. 96.]]
[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]]


- Broadcasting
    - 연산하고자 하는 배열의 모양이 다른 경우의 연산

In [33]:
arr3 = np.arange(10).reshape(5,2)
arr4 = np.arange(10).reshape(2,5)
print(arr3+arr4)

#에러 확인 맞음 - arr3와 arr4 shape이 맞지 않아 연산이 불가능함

ValueError: operands could not be broadcast together with shapes (5,2) (2,5) 

In [35]:
#배열과 스칼라의 연산
scalar = 10
vector = np.array([1,2,3])

print(scalar + vector)

[11 12 13]


In [38]:
scalar = 10
metrix = np.array([[1,2,3],[4,5,6]])

print(scalar + metrix)

[[11 12 13]
 [14 15 16]]


In [41]:
scalar = 10
tensor = np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]],
                   [[13,14,15],[16,17,18]]])

print(scalar + tensor)

[[[11 12 13]
  [14 15 16]]

 [[17 18 19]
  [20 21 22]]

 [[23 24 25]
  [26 27 28]]]


In [54]:
#broadcasting의 조건
# 벡터와 매트릭스의 연산
matrix = np.arange(1,10).reshape(3,3)
vector = np.arange(11,14).reshape(1,3)

print(matrix)
print(vector)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]]


In [55]:
print(matrix + vector)

[[12 14 16]
 [15 17 19]
 [18 20 22]]


In [56]:
matrix = np.arange(1,10).reshape(3,3)
vector = np.arange(11,14).reshape(3,1)

print(matrix)
print(vector)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11]
 [12]
 [13]]


In [57]:
print(matrix + vector)

[[12 13 14]
 [16 17 18]
 [20 21 22]]


In [59]:
#벡터와 벡터의 브로드캐스팅 연산
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3]).reshape(3,1)
print(arr1)
print(arr2)

[1 2 3]
[[1]
 [2]
 [3]]


In [62]:
print(arr1+arr2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# 행렬연산
### np.dot(arr1,arr2)

In [68]:
arr1= np.array([1,2,3])
arr2 = np.array([1,2,3])
print(arr1*arr2)

[1 4 9]


In [70]:
arr1= np.array([1,2,3])
arr2 = np.array([1,2,3]).T
print(np.dot(arr1,arr2))
print(arr1*arr2)

14
[1 4 9]


In [72]:
print(np.dot(arr1,arr2))
print(arr1.dot(arr2))
print(arr1@arr2)

14
14
14


In [73]:
arr3 = np.arange(1,7).reshape(2,3)
arr4 = np.arange(11,17).reshape(3,2)
print(np.dot(arr3,arr4))

[[ 82  88]
 [199 214]]
