In [6]:
import numpy as np

# 파일 처리
- ndarray의 정보를 파일로 저장할 수 있다
- 일반적인 파일 확장자는 npy를 사용한다

In [7]:
n = np.random.randn(3,5)
print(n)
n.tofile('n.npy')   # tofile 파일 저장

[[ 0.52869998  0.24002431  1.2128991  -1.10488172 -0.77255987]
 [-2.23883153 -0.29351768  1.21995378  0.72245015  1.44879789]
 [-0.31375817 -0.03495561  0.74840012 -0.02521824 -1.69088776]]


In [8]:
m = np.fromfile('n.npy')  # fromfile 파일 불러오기
print(m)

[ 0.52869998  0.24002431  1.2128991  -1.10488172 -0.77255987 -2.23883153
 -0.29351768  1.21995378  0.72245015  1.44879789 -0.31375817 -0.03495561
  0.74840012 -0.02521824 -1.69088776]


In [9]:
np.fromfile('C:/STUDY/StudyPython22/jupyter/n.npy')  #절대경로로 불러오기- 배열이 깨지는 문제
print(m)

[ 0.52869998  0.24002431  1.2128991  -1.10488172 -0.77255987 -2.23883153
 -0.29351768  1.21995378  0.72245015  1.44879789 -0.31375817 -0.03495561
  0.74840012 -0.02521824 -1.69088776]


In [10]:
np.fromfile('C:/STUDY/StudyPython22/jupyter/n.npy').reshape(3,5)  #파일의 형태 그대로 불러오기
print(m)

[ 0.52869998  0.24002431  1.2128991  -1.10488172 -0.77255987 -2.23883153
 -0.29351768  1.21995378  0.72245015  1.44879789 -0.31375817 -0.03495561
  0.74840012 -0.02521824 -1.69088776]


In [11]:
np.save('n1.npy',n)
m1 = np.load('n1.npy')
print(m1)

[[ 0.52869998  0.24002431  1.2128991  -1.10488172 -0.77255987]
 [-2.23883153 -0.29351768  1.21995378  0.72245015  1.44879789]
 [-0.31375817 -0.03495561  0.74840012 -0.02521824 -1.69088776]]


- txt 파일 저장(np.savetxt)
- txt 파일 불러오기(np.loadtxt)


In [12]:
np.savetxt('n.txt',n)

In [14]:
np.loadtxt('n.txt')

array([[ 0.52869998,  0.24002431,  1.2128991 , -1.10488172, -0.77255987],
       [-2.23883153, -0.29351768,  1.21995378,  0.72245015,  1.44879789],
       [-0.31375817, -0.03495561,  0.74840012, -0.02521824, -1.69088776]])

In [18]:
#csv 파일 저장, 불러오기
np.savetxt('n.csv',n) #한 셀에 ,로 구분되어 전체 데이터가 들어감

np.savetxt('n.csv', n, delimiter= ',') # 각 셀로 데이터가 들어감

In [17]:
np.loadtxt('n.csv')

array([[ 0.52869998,  0.24002431,  1.2128991 , -1.10488172, -0.77255987],
       [-2.23883153, -0.29351768,  1.21995378,  0.72245015,  1.44879789],
       [-0.31375817, -0.03495561,  0.74840012, -0.02521824, -1.69088776]])

- 문제 풀이

In [58]:
arr = np.arange(1,26,dtype=np.int8).reshape(5,5) # 1~25 범위의 5x5 행렬 생성
print(arr)
np.savetxt('./data/data.csv', arr, delimiter=',')


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [53]:
arr1 = np.loadtxt('./data/06_data1.txt',dtype=np.str_)
arr1

arr1 = np.loadtxt('./data/06_data1.txt',delimiter='\t', dtype=np.str_)
print(arr1)

[['1' '15' '14' '4']
 ['12' '6' '7' '9']
 ['8' '10' '11' '5']
 ['13' '3' '2' '16']]


In [57]:
arr2 = np.loadtxt('./data/06_data2.txt',delimiter=',', dtype=np.int8)
print(arr2)

[[ 1 15 14  4]
 [12  6  7  9]
 [ 8 10 11  5]
 [13  3  2 16]]


- 파일 읽어오기

In [65]:
data = np.loadtxt('./data/ex1_지역별전기요금.csv',delimiter=',',dtype=np.int32)
print(data[  :5  , : ]) #상위 5개 데이터 출력

[[      1  565082     273   27177]
 [      2 2827233     444   45111]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      5  380425     391   38020]]


- 데이터 확인하기

In [67]:
print(data.shape)

(17, 4)


In [73]:
#중복지역확인
print(np.unique(data[:,0]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [74]:
#sort를 활용한 정렬 -- > 행렬의 값을 다 섞어버리기 때문에 제대로된 데이터를 추출할 수 없음
#2차원 배열의 행과 열로 되어있는 데이터에서는 sort를 최대한 사용하지 않는게 좋음
print(np.sort(data[:,1]))

[  49394  258605  323151  380425  425659  565082  584500  634696  668623
  726699  734723  742285  947300 1131034 1144913 2737725 2827233]


In [81]:
#정렬(argsort 사용) - 가구수를 기준으로 오름차순으로 정렬
print(data[:,1].argsort())
print(data[ data[:,1].argsort() ])

#argsort를 사용하여 내림차순으로 정렬
print(data[:,1].argsort()[::-1] )
print(data[ data[:,1].argsort()[::-1] ])

[ 9 14 10  4  6  0 16 13  5 12 11 15  7  3  2  8  1]
[[     10   49394     580   57091]
 [     15  258605     221   22180]
 [     11  323151     353   35470]
 [      5  380425     391   38020]
 [      7  425659     344   32331]
 [      1  565082     273   27177]
 [     17  584500     268   26899]
 [     14  634696     285   28556]
 [      6  668623     364   35245]
 [     13  726699     249   25120]
 [     12  734723     398   40049]
 [     16  742285     282   27901]
 [      8  947300     366   36274]
 [      4 1131034     230   22436]
 [      3 1144913     289   29043]
 [      9 2737725     361   36569]
 [      2 2827233     444   45111]]
[ 1  8  2  3  7 15 11 12  5 13 16  0  6  4 10 14  9]
[[      2 2827233     444   45111]
 [      9 2737725     361   36569]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      8  947300     366   36274]
 [     16  742285     282   27901]
 [     12  734723     398   40049]
 [     13  726699     249   25120]
 [      6  668623 

In [82]:
#fancy index
print(data[data[:,1].argsort()])

[[     10   49394     580   57091]
 [     15  258605     221   22180]
 [     11  323151     353   35470]
 [      5  380425     391   38020]
 [      7  425659     344   32331]
 [      1  565082     273   27177]
 [     17  584500     268   26899]
 [     14  634696     285   28556]
 [      6  668623     364   35245]
 [     13  726699     249   25120]
 [     12  734723     398   40049]
 [     16  742285     282   27901]
 [      8  947300     366   36274]
 [      4 1131034     230   22436]
 [      3 1144913     289   29043]
 [      9 2737725     361   36569]
 [      2 2827233     444   45111]]


- 데이터 통계

In [83]:
#전국 대상 가구수(1 열) 합
print(np.sum(data[:,1])) #data[:,1].sum()

14882047


In [91]:
# 가구당 평균 전력 사용량 (2 열)의 전국 평균값
print(round(data[:,2].mean(),2))   # round(  , 소수점자리수지정) - 반올림하여 출력
                                   # np.mean(data[:2])

335.18


In [101]:
#무식하게 평균 구하기
e_sum = np.sum(data[:,2])
print(e_sum)

n_rows = data.shape[0]

print('가구당 평균 전력 사용량의 전국 평균값 :' , round(e_sum/n_rows,2))

5698
가구당 평균 전력 사용량의 전국 평균값 : 335.18


In [112]:
#가구당 평균 전력 사용량(2열)이 평균 이상인 지역
#대상가구수추출(1열)
avg_=data[:,2].mean()  #가구당 평균 전력사용량의 전국 평균

print(data[: , 2]>avg_)
print(data[data[: , 2]>avg_ , 0:2]) #슬라이싱 [ , 0:2] (1열까지 추출)

[False  True False False  True  True  True  True  True  True  True  True
 False False False False False]
[[      2 2827233]
 [      5  380425]
 [      6  668623]
 [      7  425659]
 [      8  947300]
 [      9 2737725]
 [     10   49394]
 [     11  323151]
 [     12  734723]]
