# [문제1] 위 파일을 읽어보고 상위 3개의 (발생년도, 발생건수, 구성비)의 데이터를 추출해 봅시다.

In [3]:
import numpy as np

In [57]:
data = np.loadtxt('./data/ex2_전년대비_시도별_교통사망사고.csv',delimiter=',',dtype = float)
print(data[ :3, [ 0, 2, 3 ]]) # 필요한 열의 값을 인덱싱으로 추출

[[2014.   218.     4.8]
 [2014.   872.    19. ]
 [2014.   401.     8.7]]


# [문제2] 위 데이터에서 부산에서 발생한 교통사망사고 모든 현황을 추출해 봅시다.

In [59]:
print(data[data[:,1]==8,    ])

[[2014.     8.   163.     3.6  -47.   -22.4]]


# [문제3] 위 데이터에서 전국 사고 발생건수의 합계와 전국 평균을 계산해 봅시다.

In [60]:
print('전국 사고 발생건수 합계: ', data[:,2].sum())
print('전국 사고 발생건수 평균 : ', round(data[:,2].mean(),2))

전국 사고 발생건수 합계:  4583.0
전국 사고 발생건수 평균 :  269.59


# [문제4] 위 데이터에서 교통사고 증감수가 가장 큰 지역의 모든 현황을 추출해 봅시다.

In [66]:
#argmax
print(data[data[:,4].argmax(),:])

#max
print(data[data[:,4] == max(data[:,4])])

[2014.     6.   182.     4.    19.    11.7]
[[2014.     6.   182.     4.    19.    11.7]]


# [문제5] 위 데이터에서 교통사고 증감률이 가장 작은 지역의 모든 현황을 추출해 봅시다.

In [74]:
#argmin
print(data[data[:,5].argmin(),:])

#min
print(data[data[:,5] == min( data[ :,5] )])

[2014.     8.   163.     3.6  -47.   -22.4]
[[2014.     8.   163.     3.6  -47.   -22.4]]


# [문제6] 위 데이터에서 사고 발생 건수가 400건 이상인 곳의 지역과 교통사고 발생건수, 증감수, 증감률을 추출해 봅시다.

In [79]:
print(data[:,2]>=400)

#print(data[data[:,2]>=400 , 2:6]) #슬라이싱은 가능

print(data[data[:,2]>=400 , ][:,[2,4,5]])  # 별도 인덱싱 처리


data2 = data[data[:,2]>=400 , ] # 변수로 처리
print(data2[:,[2,4,5]])

[False  True  True  True False False False False False False False False
  True False False False False]
[[872.  -45.   -4.9]
 [401.  -45.  -10.1]
 [464.  -41.   -8.1]
 [400.  -35.   -8. ]]
[[872.  -45.   -4.9]
 [401.  -45.  -10.1]
 [464.  -41.   -8.1]
 [400.  -35.   -8. ]]
